# coding: utf-8

# flake8: noqa
"""
    MLP API

    API Guide for accessing MLP API

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from caraml.mlp.client.models.application import Application
from caraml.mlp.client.models.application_config import ApplicationConfig
from caraml.mlp.client.models.application_config_navigation_inner import (
    ApplicationConfigNavigationInner,
)
from caraml.mlp.client.models.label import Label
from caraml.mlp.client.models.project import Project
from caraml.mlp.client.models.secret import Secret
from caraml.mlp.client.models.secret_storage import SecretStorage
from caraml.mlp.client.models.secret_storage_config import SecretStorageConfig
from caraml.mlp.client.models.vault_secret_storage_config import (
    VaultSecretStorageConfig,
)
