# coding: utf-8

# flake8: noqa
"""
    Turing Minimal Openapi Spec for SDK

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from routers.client.models.autoscaling_policy import AutoscalingPolicy
from routers.client.models.big_query_config import BigQueryConfig
from routers.client.models.big_query_dataset import BigQueryDataset
from routers.client.models.big_query_dataset_config import BigQueryDatasetConfig
from routers.client.models.big_query_sink import BigQuerySink
from routers.client.models.big_query_sink_config import BigQuerySinkConfig
from routers.client.models.dataset import Dataset
from routers.client.models.default_traffic_rule import DefaultTrafficRule
from routers.client.models.enricher import Enricher
from routers.client.models.ensembler import Ensembler
from routers.client.models.ensembler_config import EnsemblerConfig
from routers.client.models.ensembler_config_kind import EnsemblerConfigKind
from routers.client.models.ensembler_docker_config import EnsemblerDockerConfig
from routers.client.models.ensembler_infra_config import EnsemblerInfraConfig
from routers.client.models.ensembler_job_status import EnsemblerJobStatus
from routers.client.models.ensembler_pyfunc_config import EnsemblerPyfuncConfig
from routers.client.models.ensembler_standard_config import EnsemblerStandardConfig
from routers.client.models.ensembler_standard_config_experiment_mappings_inner import EnsemblerStandardConfigExperimentMappingsInner
from routers.client.models.ensembler_type import EnsemblerType
from routers.client.models.ensemblers_paginated_results import EnsemblersPaginatedResults
from routers.client.models.ensembling_job import EnsemblingJob
from routers.client.models.ensembling_job_ensembler_spec import EnsemblingJobEnsemblerSpec
from routers.client.models.ensembling_job_ensembler_spec_result import EnsemblingJobEnsemblerSpecResult
from routers.client.models.ensembling_job_meta import EnsemblingJobMeta
from routers.client.models.ensembling_job_paginated_results import EnsemblingJobPaginatedResults
from routers.client.models.ensembling_job_prediction_source import EnsemblingJobPredictionSource
from routers.client.models.ensembling_job_result_type import EnsemblingJobResultType
from routers.client.models.ensembling_job_sink import EnsemblingJobSink
from routers.client.models.ensembling_job_source import EnsemblingJobSource
from routers.client.models.ensembling_job_spec import EnsemblingJobSpec
from routers.client.models.ensembling_resources import EnsemblingResources
from routers.client.models.env_var import EnvVar
from routers.client.models.event import Event
from routers.client.models.experiment_config import ExperimentConfig
from routers.client.models.field_source import FieldSource
from routers.client.models.generic_dataset import GenericDataset
from routers.client.models.generic_ensembler import GenericEnsembler
from routers.client.models.generic_sink import GenericSink
from routers.client.models.id_object import IdObject
from routers.client.models.kafka_config import KafkaConfig
from routers.client.models.label import Label
from routers.client.models.log_level import LogLevel
from routers.client.models.pagination_paging import PaginationPaging
from routers.client.models.project import Project
from routers.client.models.protocol import Protocol
from routers.client.models.py_func_ensembler import PyFuncEnsembler
from routers.client.models.resource_request import ResourceRequest
from routers.client.models.result_logger_type import ResultLoggerType
from routers.client.models.route import Route
from routers.client.models.router import Router
from routers.client.models.router_config import RouterConfig
from routers.client.models.router_details import RouterDetails
from routers.client.models.router_ensembler_config import RouterEnsemblerConfig
from routers.client.models.router_events import RouterEvents
from routers.client.models.router_id_and_version import RouterIdAndVersion
from routers.client.models.router_id_object import RouterIdObject
from routers.client.models.router_status import RouterStatus
from routers.client.models.router_version import RouterVersion
from routers.client.models.router_version_config import RouterVersionConfig
from routers.client.models.router_version_config_log_config import RouterVersionConfigLogConfig
from routers.client.models.router_version_log_config import RouterVersionLogConfig
from routers.client.models.router_version_status import RouterVersionStatus
from routers.client.models.save_mode import SaveMode
from routers.client.models.traffic_rule import TrafficRule
from routers.client.models.traffic_rule_condition import TrafficRuleCondition
