# coding: utf-8

# flake8: noqa
"""
    Merlin

    API Guide for accessing Merlin's model management, deployment, and serving functionalities

    The version of the OpenAPI document: 0.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from caraml.models.client.models.alert_condition_metric_type import (
    AlertConditionMetricType,
)
from caraml.models.client.models.alert_condition_severity import AlertConditionSeverity
from caraml.models.client.models.autoscaling_policy import AutoscalingPolicy
from caraml.models.client.models.binary_classification_output import (
    BinaryClassificationOutput,
)
from caraml.models.client.models.config import Config
from caraml.models.client.models.container import Container
from caraml.models.client.models.custom_predictor import CustomPredictor
from caraml.models.client.models.deployment_mode import DeploymentMode
from caraml.models.client.models.endpoint_status import EndpointStatus
from caraml.models.client.models.env_var import EnvVar
from caraml.models.client.models.environment import Environment
from caraml.models.client.models.file_format import FileFormat
from caraml.models.client.models.gpu_config import GPUConfig
from caraml.models.client.models.gpu_toleration import GPUToleration
from caraml.models.client.models.label import Label
from caraml.models.client.models.logger import Logger
from caraml.models.client.models.logger_config import LoggerConfig
from caraml.models.client.models.logger_mode import LoggerMode
from caraml.models.client.models.metrics_type import MetricsType
from caraml.models.client.models.mock_response import MockResponse
from caraml.models.client.models.model import Model
from caraml.models.client.models.model_endpoint import ModelEndpoint
from caraml.models.client.models.model_endpoint_alert import ModelEndpointAlert
from caraml.models.client.models.model_endpoint_alert_condition import (
    ModelEndpointAlertCondition,
)
from caraml.models.client.models.model_endpoint_rule import ModelEndpointRule
from caraml.models.client.models.model_endpoint_rule_destination import (
    ModelEndpointRuleDestination,
)
from caraml.models.client.models.model_prediction_config import ModelPredictionConfig
from caraml.models.client.models.model_prediction_output import ModelPredictionOutput
from caraml.models.client.models.model_prediction_output_class import (
    ModelPredictionOutputClass,
)
from caraml.models.client.models.model_schema import ModelSchema
from caraml.models.client.models.operation_tracing import OperationTracing
from caraml.models.client.models.pipeline_tracing import PipelineTracing
from caraml.models.client.models.prediction_job import PredictionJob
from caraml.models.client.models.prediction_job_config import PredictionJobConfig
from caraml.models.client.models.prediction_job_config_bigquery_sink import (
    PredictionJobConfigBigquerySink,
)
from caraml.models.client.models.prediction_job_config_bigquery_source import (
    PredictionJobConfigBigquerySource,
)
from caraml.models.client.models.prediction_job_config_gcs_sink import (
    PredictionJobConfigGcsSink,
)
from caraml.models.client.models.prediction_job_config_gcs_source import (
    PredictionJobConfigGcsSource,
)
from caraml.models.client.models.prediction_job_config_model import (
    PredictionJobConfigModel,
)
from caraml.models.client.models.prediction_job_config_model_result import (
    PredictionJobConfigModelResult,
)
from caraml.models.client.models.prediction_job_resource_request import (
    PredictionJobResourceRequest,
)
from caraml.models.client.models.prediction_logger_config import PredictionLoggerConfig
from caraml.models.client.models.project import Project
from caraml.models.client.models.protocol import Protocol
from caraml.models.client.models.ranking_output import RankingOutput
from caraml.models.client.models.regression_output import RegressionOutput
from caraml.models.client.models.resource_request import ResourceRequest
from caraml.models.client.models.result_type import ResultType
from caraml.models.client.models.save_mode import SaveMode
from caraml.models.client.models.schema_spec import SchemaSpec
from caraml.models.client.models.secret import Secret
from caraml.models.client.models.standard_transformer_simulation_request import (
    StandardTransformerSimulationRequest,
)
from caraml.models.client.models.standard_transformer_simulation_response import (
    StandardTransformerSimulationResponse,
)
from caraml.models.client.models.transformer import Transformer
from caraml.models.client.models.value_type import ValueType
from caraml.models.client.models.version import Version
from caraml.models.client.models.version_endpoint import VersionEndpoint
