name: CaraML Auth Google CI

on:
  # Automatically run CI on Release and Pre-Release tags and main branch
  # (except changes to non-relevant paths)
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
    branches:
      - main
    paths:
      - "packages/caraml-auth-google/**"
      - ".github/workflows/caraml-sdk.yaml"

  # Automatically run CI on branches, that have active PR opened
  pull_request:
    branches:
      - main
    paths:
      - "packages/caraml-auth-google/**"
      - ".github/workflows/caraml-sdk.yaml"

  # To make it possible to trigger e2e CI workflow for any arbitrary git ref
  workflow_dispatch:

env:
  ARTIFACT_RETENTION_DAYS: 7

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10" ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true

      - name: Cache Conda environment
        uses: actions/cache@v2
        with:
          path: engines/pyfunc-ensembler-service/env
          key: |
            conda-${{ hashFiles('engines/pyfunc-ensembler-service/env-${{ matrix.python-version }}.yaml') }}-${{ hashFiles('engines/pyfunc-ensembler-service/requirements.txt') }}-${{ hashFiles('engines/pyfunc-ensembler-service/requirements.dev.txt') }}
          restore-keys: conda-

      - name: Run Tests
        working-directory: engines/pyfunc-ensembler-service
        run: |
          make setup
          make test